### ISSUE TITLE
Bots not being blocked and Exceptions

### ISSUE THREAD

**Issue by taharushain** [danmoz/django-fake-bot-detector#5]
Bots are not being blocked and I am getting following error on my web app. Is there something that I am doing wrong?

```
django-killbot cannot check any client IP addresses because request.META['REMOTE_ADDR'] is missing, your webserver may be misconfigured.

File "/home/ubuntu/kohyari/kohyarienv/lib/python3.6/site-packages/fakebotdetector/middleware.py", line 30, in <listcomp>
Jun 17 13:17:41 kohyari gunicorn[10752]:     matched_sigs = [sig for sig in self.BOTS if sig[0].lower() in user_agent.lower()]
Jun 17 13:17:41 kohyari gunicorn[10752]: AttributeError: 'NoneType' object has no attribute 'lower'
```

My middleware config looks like this in settings.py

```
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'fakebotdetector.middleware.FakeBotDetectorMiddleware',
    'django_bot_crawler_blocker.django_bot_crawler_middleware.CrawlerBlockerMiddleware',
   ...
]
```

Also, my django version is 3.0.7, is it not compatible?

**Comment by danmoz** [comment]
> user_agent = request.META.get('HTTP_USER_AGENT')

Looks like you found a bug! This is now fixed on master, I will upload a new release shortly.

> Also, my django version is 3.0.7, is it not compatible?

Django 3 should be compatible. Will update the docs to make this clearer.

**Comment by taharushain** [comment]
Thank you @danmoz  , can you also push the changes to PyPI. Also, one question, shouldn't it be better to block the IP/request in cases when the HTTP_USER_AGENT is missing or is blank as I think it shows some one behind a poorly written bot is trying to get access.

**Comment by 9mido** [comment]
@danmoz 

I also have the same concern as @taharushain someone could fake the user agent. IP address would be better. Also definitely publish the new fix to PyPi. 

https://djangosnippets.org/snippets/1865/

Read the comment of that link on why IP address is preferred compared to just user agent.
